### ISSUE TITLE
Collect Docker events

### ISSUE THREAD

**Issue by otisg** [sematext/spm-agent-docker#1]
Docker remote API has /events endpoint, which you GET, providing the timestamp (since) and you get back all container events: create, destroy, die, export, kill, pause, restart, start, stop, unpause:
https://docs.docker.com/v1.6/reference/api/docker_remote_api_v1.6/#monitor-dockers-events

Would be good to get those into SPM as Events via this API: https://sematext.atlassian.net/wiki/display/PUBSPM/Events+Integration

**Comment by megastef** [comment]
https://github.com/sematext/spm-agent-docker/commit/7953b4647fcfe5e6edae8f575aa5b7f19dc5dc43 implements docker events using https://github.com/sematext/spm-metrics-js  
![](https://sematext.files.wordpress.com/2015/06/docker-events.png)

**Comment by otisg** [comment]
Awesome!  Any idea what are all possible event types?  Something to add to the README?

**Comment by megastef** [comment]
Improved - mapped docker status to event type. 
Following events are generated:
- server-info - created by spm-agent framework with node.js and OS version info on startup
- docker-info - Docker Version, API Version, Kernel Version on startup
- create - Docker Status
- destroy - Docker Status
- start - Docker Status
- stop - Docker Status
- die - Docker Status

![](https://sematext.files.wordpress.com/2015/06/docker-events-3.png)
