### ISSUE TITLE
Add a diagnostics tool

### ISSUE THREAD

**Issue by otisg** [sematext/spm-agent-docker#6]
When things don't work as they should, it's handy to have a tool that can collect diagnostics info.

**Comment by megastef** [comment]
Updated spm-client-diagnostics script. 

```
docker exec -it spm-agent spm-client-diagnostics > spm-diagnostics.txt
```

A little update (path of genereated zip file), will go into sematext/sematext-agent-docker, with the next release.  Then the info can be copied used "docker cp".

**Comment by otisg** [comment]
Should https://sematext.atlassian.net/wiki/display/PUBSPM/SPM+for+Node.js#SPMforNode.js-GeneratediagnosticsfileforSematextSupport be updated?

**Comment by megastef** [comment]
Update: https://sematext.atlassian.net/wiki/display/PUBSPM/SPM+for+Docker
